<a href="https://colab.research.google.com/github/Ajayrajpurohit/dot-slash/blob/master/LR_ambala.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Installing required library**

In [103]:
!pip install sklearn

**Importing libraries**

In [0]:
import pandas as pd
import numpy as np
import io

In [105]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [0]:
df=pd.read_csv('gdrive/My Drive/logisticregression.csv')


In [143]:
df

Area Name Rural/Urban  Total Population  \
0          Sub-Dist - Bawani Khera       Rural            106746   
1          Sub-Dist - Bawani Khera       Urban             20289   
2                      Rohnat (35)       Rural              3785   
3                      Ratera (34)       Rural              5572   
4                       Bohal (37)       Rural              1919   
5                       Siper (36)       Rural              2441   
6                    Jamalpur (40)       Rural              8846   
7                      Paposa (41)       Rural              3731   
8                Aurangnagar (134)       Rural               387   
9                      Barsi (133)       Rural             23327   
10                    Siwana (132)       Rural              5478   
11        Bawani Khera (Rural)(42)       Rural               906   
12                    Baliali (44)       Rural             12440   
13                   Ramupura (27)       Rural              1977   
14                        Sui (46)       Rural              5063   
15                       Taga (45)       Rural                45   
16                Lohari Jatu (47)       Rural              8971   
17                Sumra Khera (43)       Rural               875   
18                        Pur (49)       Rural              6961   
19                     Siwara (50)       Rural              4176   
20                    Kungar (131)       Rural              9846   
21               Bawani khera (MC)       Urban             20289   
22   Bawani khera (MC) - Ward No.1       Urban              1707   
23   Bawani khera (MC) - Ward No.2       Urban              1407   
24   Bawani khera (MC) - Ward No.3       Urban              1398   
25   Bawani khera (MC) - Ward No.4       Urban              1525   
26   Bawani khera (MC) - Ward No.5       Urban              1178   
27   Bawani khera (MC) - Ward No.6       Urban              2144   
28   Bawani khera (MC) - Ward No.7       Urban              1626   
29   Bawani khera (MC) - Ward No.8       Urban              2609   
..                             ...         ...               ...   
522             Mandhi Piranu (20)       Rural              1100   
523               Mandi Kehar (22)       Rural              1593   
524                 Jagrambass(24)       Rural              1975   
525                       Huee(23)       Rural              1566   
526                    Dalawas(36)       Rural               965   
527                       Gopi(35)       Rural              2056   
528                 Pachganwa(173)       Rural               847   
529                  Kari Modh(43)       Rural              1783   
530                Kari Dharni(42)       Rural              1668   
531                     Badhra(40)       Rural              6333   
532                     Jewali(37)       Rural              3161   
533                      Berla(19)       Rural              6974   
534                Kubja Nagar(17)       Rural               919   
535                       Todi(18)       Rural              1855   
536                    Dagroli(63)       Rural              3019   
537                     Kanhra(62)       Rural              1696   
538                      Nimar(61)       Rural              1896   
539                   Kiskanda(56)       Rural              1174   
540                   Chandwas(38)       Rural              1842   
541             Hansawas Khurd(39)       Rural              1814   
542             Hansawas Kalan(54)       Rural              1745   
543                    Bhandwa(41)       Rural              3306   
544                     Muthra(50)       Rural               622   
545                  Surajgarh(51)       Rural               771   
546                       Lad (52)       Rural              2376   
547                     Nandha(53)       Rural              3707   
548                   Dhanasri(55)       Rural              2148   
549          

**Data Wrangling**

In [0]:
df['Rural/Urban'] = df['Rural/Urban'].str.replace('Rural', '0')
df['Rural/Urban'] = df['Rural/Urban'].str.replace('Urban', '1')

**Logistic Regression**

In [0]:
# Importing the dataset and scaling down the features section 
dataset = df
X = dataset.iloc[:, [2,3,4,6,15,17,19,27,29,30,31,34,37,40,45]].values
y = dataset.iloc[:, 1].values

In [145]:
#Selecting 15 features from the table resulting in following dataframe
X = dataset.iloc[:, [2,3,4,6,15,17,19,27,29,30,31,34,37,40,45]]
X

Total Population  Good Households  Livable Households  \
0              106746             40.6                53.2   
1               20289             41.9                54.2   
2                3785             39.2                53.7   
3                5572             77.6                20.8   
4                1919             52.6                44.9   
5                2441             49.8                46.5   
6                8846             49.1                47.8   
7                3731             36.6                56.1   
8                 387             18.8                81.2   
9               23327             36.4                55.5   
10               5478             30.9                59.5   
11                906             19.2                80.8   
12              12440             32.8                59.1   
13               1977             34.4                62.0   
14               5063             36.1                55.6   
15                 45            100.0                 0.0   
16               8971             33.5                57.8   
17                875             73.6                26.4   
18               6961             29.5                68.2   
19               4176             47.9                48.1   
20               9846             47.4                46.8   
21              20289             41.9                54.2   
22               1707             33.0                65.4   
23               1407              7.9                90.5   
24               1398             62.5                35.6   
25               1525             49.2                50.2   
26               1178             33.8                54.6   
27               2144              8.9                79.8   
28               1626             49.2                46.2   
29               2609             34.0                63.8   
..                ...              ...                 ...   
522              1100             46.7                52.4   
523              1593             88.1                11.2   
524              1975             64.3                35.1   
525              1566             58.0                41.0   
526               965             77.8                22.2   
527              2056             32.3                64.1   
528               847             59.2                36.8   
529              1783             53.2                41.4   
530              1668             80.6                19.1   
531              6333             35.3                62.4   
532              3161             36.7                61.9   
533              6974             62.6                36.3   
534               919             70.2                26.7   
535              1855             56.7                42.2   
536              3019             75.8                23.2   
537              1696             45.9                48.3   
538              1896             44.6                54.9   
539              1174             39.2                60.4   
540              1842             33.1                62.9   
541              1814             76.0                22.5   
542              1745              4.4                91.2   
543              3306             51.0                44.0   
544               622             88.4                11.6   
545               771             98.0                 2.0   
546              2376             71.2                28.8   
547              3707             83.3                16.1   
548              2148             59.4                39.7   
549              7370             42.9                54.6   
550              2669             63.5                34.3   
551              2515             21.4                63.7   

     Tapwater from treated source  Sources of Lighting -Electricity  \
0                            60.2                              86.3   
1                 

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [0]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [148]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm


array([[92,  4],
       [ 6,  9]])

**Accuracy=(92+1)/(92+1+6+4)**

**USE THE INDEX(0-14) OF THIS DICTIONARY BELOW TO REFER TO THE FEATURES THROUGHOUT THE ANALYSIS **

In [0]:
p_dict = {0:"Total Population", 1:"Good Households", 2:"Livable Households",3:"Tapwater from treated source",4:"Sources of Lighting -Electricity",5:"Sources of Lighting -Solar energy",6:"Number of households having latrine facility within the premises",7:"Bathroom",8:"Waste Water Closed drainage",9:"Waste Water Open drainage",10:"Good Fuels",11:"Radio/Transistor",12:"Computer/Laptop Without Internet",13:"Both Mobile and Landline",14:"Types of Structure of houses-Permanent"}

**In above array we can see the weighted factors affecting our output for the training data index at 0**

**In above example we can see that the lowest value is at 6th index and the algorithm predicted it to be a rural area hence we can conclude that the feature *Number of households having latrine facility within the premises* is mainly responsible for that area to be classified as a Rural one **

**If we had predicted above example as 1 i.e URBAN we should check which index is of the highest value and use dict_p to conclude the feature mainly responsible for it to get classified as urban area**

**CONSIDERING OVERALL STATE**

In [0]:
#Taking Overall Data for HARYANA STATE
classifier.coef_

array([[-0.02337898, -0.55637772, -0.38235592,  0.62167736, -0.82975536,
         0.15613961,  1.40820356, -0.56117186,  0.32891618, -0.08945408,
         2.06863021, -0.54971904,  0.03170474,  0.60019666, -0.40526955]])

In [0]:
from sklearn.feature_selection import RFE
rfe = RFE(classifier, 1)
fit = rfe.fit(X_train, y_train)
#print("fit.n_features_")
#print("Selected Features: %s") % fit.support_
print(fit.ranking_) 

[15 10 11  5  3 12  2  4  9 13  1  6 14  7  8]


In [0]:
p_dict = {0:"Total Population", 1:"Good Households", 2:"Livable Households",3:"Tapwater from treated source",4:"Sources of Lighting -Electricity",5:"Sources of Lighting -Solar energy",6:"Number of households having latrine facility within the premises",7:"Bathroom",8:"Waste Water Closed drainage",9:"Waste Water Open drainage",10:"Good Fuels",11:"Radio/Transistor",12:"Computer/Laptop Without Internet",13:"Both Mobile and Landline",14:"Types of Structure of houses-Permanent"}

**Areas in which the government needs to focus**

In [141]:
p_dict[0],p_dict[9],p_dict[12]

('Total Population',
 'Waste Water Open drainage',
 'Computer/Laptop Without Internet')

**Using above ranking system we can say that 10th index feature (*Good Fuel*) becomes an important factor for classifying areas of HARYANA as URBAN and the the government should focus on improving features at index 0 ,9,12 which ranked 15,13,14. **

**CONCLUSION FOR HARYANA STATE**



*   The government is not able to provide a enough facilities to its population.
*  The government/organisation should built proper drainage system and close them.
*   Also the Telecom department should should ensure to lay internet cables or Prvate companies should built Towers in the state of HARYANA 




**FOR CONCLUDING A PARTICULAR AREA**


*   Similar analysis can be done at ward level for the state of Haryana
*  If the central governent wants to provide amenities we can do the same analysis State wise .(Here the analysis is done on Ward levels.)



In [151]:
y_test[0]

'Rural'

In [154]:
y_pred[0]

'Rural'

In [155]:
X_test[0]*classifier.coef_

array([[ 0.00464745,  0.6392857 , -0.15675646, -0.34737337,  1.78358399,
        -0.0388394 , -1.14798598,  0.67891241, -0.14532549,  0.01572259,
        -0.25678894,  0.28498915, -0.0040409 , -0.42588348,  0.79330222]])

**In above array we can see the weighted factors affecting our output for the training data index at 0**

**In above example we can see that the lowest value is at 6th index and the algorithm predicted it to be a rural area hence we can conclude that the feature *Number of households having latrine facility within the premises* is mainly responsible for that area to be classified as a Rural one **

**If we had correctly predicted above example as 1 i.e URBAN we should check which index is of the highest value and use dict_p to conclude the feature mainly responsible for it to get classified as urban area**